.PHONY: clean All

All:
	@echo "----------Building project:[ ChallengeSolution - Debug ]----------"
	@"$(MAKE)" -f  "ChallengeSolution.mk"
clean:
	@echo "----------Cleaning project:[ ChallengeSolution - Debug ]----------"
	@"$(MAKE)" -f  "ChallengeSolution.mk" clean
